argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.1
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      hosts: argocd.192.168.1.10.nip.io
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo
          url: https://argoproj.github.io/argo-helm